// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	runtime "github.com/wernsiet/morchy/pkg/runtime"

	workload "github.com/wernsiet/morchy/pkg/controlplane/domain/workload"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateLease provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRepository) CreateLease(_a0 context.Context, _a1 string, _a2 string) (*workload.Lease, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateLease")
	}

	var r0 *workload.Lease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*workload.Lease, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *workload.Lease); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workload.Lease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLease'
type MockRepository_CreateLease_Call struct {
	*mock.Call
}

// CreateLease is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockRepository_Expecter) CreateLease(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockRepository_CreateLease_Call {
	return &MockRepository_CreateLease_Call{Call: _e.mock.On("CreateLease", _a0, _a1, _a2)}
}

func (_c *MockRepository_CreateLease_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockRepository_CreateLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_CreateLease_Call) Return(_a0 *workload.Lease, _a1 error) *MockRepository_CreateLease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateLease_Call) RunAndReturn(run func(context.Context, string, string) (*workload.Lease, error)) *MockRepository_CreateLease_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkload provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) CreateWorkload(_a0 context.Context, _a1 workload.Workload) (*workload.Workload, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkload")
	}

	var r0 *workload.Workload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, workload.Workload) (*workload.Workload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, workload.Workload) *workload.Workload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workload.Workload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, workload.Workload) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkload'
type MockRepository_CreateWorkload_Call struct {
	*mock.Call
}

// CreateWorkload is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 workload.Workload
func (_e *MockRepository_Expecter) CreateWorkload(_a0 interface{}, _a1 interface{}) *MockRepository_CreateWorkload_Call {
	return &MockRepository_CreateWorkload_Call{Call: _e.mock.On("CreateWorkload", _a0, _a1)}
}

func (_c *MockRepository_CreateWorkload_Call) Run(run func(_a0 context.Context, _a1 workload.Workload)) *MockRepository_CreateWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workload.Workload))
	})
	return _c
}

func (_c *MockRepository_CreateWorkload_Call) Return(_a0 *workload.Workload, _a1 error) *MockRepository_CreateWorkload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateWorkload_Call) RunAndReturn(run func(context.Context, workload.Workload) (*workload.Workload, error)) *MockRepository_CreateWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredLeases provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) DeleteExpiredLeases(_a0 context.Context, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredLeases")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteExpiredLeases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredLeases'
type MockRepository_DeleteExpiredLeases_Call struct {
	*mock.Call
}

// DeleteExpiredLeases is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *MockRepository_Expecter) DeleteExpiredLeases(_a0 interface{}, _a1 interface{}) *MockRepository_DeleteExpiredLeases_Call {
	return &MockRepository_DeleteExpiredLeases_Call{Call: _e.mock.On("DeleteExpiredLeases", _a0, _a1)}
}

func (_c *MockRepository_DeleteExpiredLeases_Call) Run(run func(_a0 context.Context, _a1 int)) *MockRepository_DeleteExpiredLeases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_DeleteExpiredLeases_Call) Return(_a0 error) *MockRepository_DeleteExpiredLeases_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteExpiredLeases_Call) RunAndReturn(run func(context.Context, int) error) *MockRepository_DeleteExpiredLeases_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLease provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRepository) DeleteLease(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLease'
type MockRepository_DeleteLease_Call struct {
	*mock.Call
}

// DeleteLease is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockRepository_Expecter) DeleteLease(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockRepository_DeleteLease_Call {
	return &MockRepository_DeleteLease_Call{Call: _e.mock.On("DeleteLease", _a0, _a1, _a2)}
}

func (_c *MockRepository_DeleteLease_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockRepository_DeleteLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteLease_Call) Return(_a0 error) *MockRepository_DeleteLease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteLease_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_DeleteLease_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkload provides a mock function with given fields: ctx, workloadID
func (_m *MockRepository) DeleteWorkload(ctx context.Context, workloadID string) error {
	ret := _m.Called(ctx, workloadID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, workloadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkload'
type MockRepository_DeleteWorkload_Call struct {
	*mock.Call
}

// DeleteWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - workloadID string
func (_e *MockRepository_Expecter) DeleteWorkload(ctx interface{}, workloadID interface{}) *MockRepository_DeleteWorkload_Call {
	return &MockRepository_DeleteWorkload_Call{Call: _e.mock.On("DeleteWorkload", ctx, workloadID)}
}

func (_c *MockRepository_DeleteWorkload_Call) Run(run func(ctx context.Context, workloadID string)) *MockRepository_DeleteWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteWorkload_Call) Return(_a0 error) *MockRepository_DeleteWorkload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteWorkload_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// GetLease provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRepository) GetLease(_a0 context.Context, _a1 string, _a2 string) (*workload.Lease, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetLease")
	}

	var r0 *workload.Lease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*workload.Lease, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *workload.Lease); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workload.Lease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLease'
type MockRepository_GetLease_Call struct {
	*mock.Call
}

// GetLease is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockRepository_Expecter) GetLease(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockRepository_GetLease_Call {
	return &MockRepository_GetLease_Call{Call: _e.mock.On("GetLease", _a0, _a1, _a2)}
}

func (_c *MockRepository_GetLease_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockRepository_GetLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetLease_Call) Return(_a0 *workload.Lease, _a1 error) *MockRepository_GetLease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetLease_Call) RunAndReturn(run func(context.Context, string, string) (*workload.Lease, error)) *MockRepository_GetLease_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaseByWorkloadID provides a mock function with given fields: ctx, workloadID
func (_m *MockRepository) GetLeaseByWorkloadID(ctx context.Context, workloadID string) (*workload.Lease, error) {
	ret := _m.Called(ctx, workloadID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaseByWorkloadID")
	}

	var r0 *workload.Lease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*workload.Lease, error)); ok {
		return rf(ctx, workloadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *workload.Lease); ok {
		r0 = rf(ctx, workloadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workload.Lease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workloadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetLeaseByWorkloadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaseByWorkloadID'
type MockRepository_GetLeaseByWorkloadID_Call struct {
	*mock.Call
}

// GetLeaseByWorkloadID is a helper method to define mock.On call
//   - ctx context.Context
//   - workloadID string
func (_e *MockRepository_Expecter) GetLeaseByWorkloadID(ctx interface{}, workloadID interface{}) *MockRepository_GetLeaseByWorkloadID_Call {
	return &MockRepository_GetLeaseByWorkloadID_Call{Call: _e.mock.On("GetLeaseByWorkloadID", ctx, workloadID)}
}

func (_c *MockRepository_GetLeaseByWorkloadID_Call) Run(run func(ctx context.Context, workloadID string)) *MockRepository_GetLeaseByWorkloadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetLeaseByWorkloadID_Call) Return(_a0 *workload.Lease, _a1 error) *MockRepository_GetLeaseByWorkloadID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetLeaseByWorkloadID_Call) RunAndReturn(run func(context.Context, string) (*workload.Lease, error)) *MockRepository_GetLeaseByWorkloadID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkload provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) GetWorkload(_a0 context.Context, _a1 string) (*workload.Workload, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkload")
	}

	var r0 *workload.Workload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*workload.Workload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *workload.Workload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workload.Workload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkload'
type MockRepository_GetWorkload_Call struct {
	*mock.Call
}

// GetWorkload is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRepository_Expecter) GetWorkload(_a0 interface{}, _a1 interface{}) *MockRepository_GetWorkload_Call {
	return &MockRepository_GetWorkload_Call{Call: _e.mock.On("GetWorkload", _a0, _a1)}
}

func (_c *MockRepository_GetWorkload_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRepository_GetWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetWorkload_Call) Return(_a0 *workload.Workload, _a1 error) *MockRepository_GetWorkload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetWorkload_Call) RunAndReturn(run func(context.Context, string) (*workload.Workload, error)) *MockRepository_GetWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// ListEdges provides a mock function with given fields: _a0
func (_m *MockRepository) ListEdges(_a0 context.Context) ([]*workload.Edge, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListEdges")
	}

	var r0 []*workload.Edge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*workload.Edge, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*workload.Edge); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*workload.Edge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListEdges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEdges'
type MockRepository_ListEdges_Call struct {
	*mock.Call
}

// ListEdges is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockRepository_Expecter) ListEdges(_a0 interface{}) *MockRepository_ListEdges_Call {
	return &MockRepository_ListEdges_Call{Call: _e.mock.On("ListEdges", _a0)}
}

func (_c *MockRepository_ListEdges_Call) Run(run func(_a0 context.Context)) *MockRepository_ListEdges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListEdges_Call) Return(_a0 []*workload.Edge, _a1 error) *MockRepository_ListEdges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListEdges_Call) RunAndReturn(run func(context.Context) ([]*workload.Edge, error)) *MockRepository_ListEdges_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function with given fields: ctx, payloadFilters, limit
func (_m *MockRepository) ListEvents(ctx context.Context, payloadFilters map[string]string, limit int) ([]*workload.Event, error) {
	ret := _m.Called(ctx, payloadFilters, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []*workload.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, int) ([]*workload.Event, error)); ok {
		return rf(ctx, payloadFilters, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, int) []*workload.Event); ok {
		r0 = rf(ctx, payloadFilters, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*workload.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, int) error); ok {
		r1 = rf(ctx, payloadFilters, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type MockRepository_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - payloadFilters map[string]string
//   - limit int
func (_e *MockRepository_Expecter) ListEvents(ctx interface{}, payloadFilters interface{}, limit interface{}) *MockRepository_ListEvents_Call {
	return &MockRepository_ListEvents_Call{Call: _e.mock.On("ListEvents", ctx, payloadFilters, limit)}
}

func (_c *MockRepository_ListEvents_Call) Run(run func(ctx context.Context, payloadFilters map[string]string, limit int)) *MockRepository_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_ListEvents_Call) Return(_a0 []*workload.Event, _a1 error) *MockRepository_ListEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListEvents_Call) RunAndReturn(run func(context.Context, map[string]string, int) ([]*workload.Event, error)) *MockRepository_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkloads provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockRepository) ListWorkloads(_a0 context.Context, _a1 *string, _a2 *runtime.ResourceLimits, _a3 bool) ([]*workload.Workload, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkloads")
	}

	var r0 []*workload.Workload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, *runtime.ResourceLimits, bool) ([]*workload.Workload, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, *runtime.ResourceLimits, bool) []*workload.Workload); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*workload.Workload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, *runtime.ResourceLimits, bool) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkloads'
type MockRepository_ListWorkloads_Call struct {
	*mock.Call
}

// ListWorkloads is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *string
//   - _a2 *runtime.ResourceLimits
//   - _a3 bool
func (_e *MockRepository_Expecter) ListWorkloads(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockRepository_ListWorkloads_Call {
	return &MockRepository_ListWorkloads_Call{Call: _e.mock.On("ListWorkloads", _a0, _a1, _a2, _a3)}
}

func (_c *MockRepository_ListWorkloads_Call) Run(run func(_a0 context.Context, _a1 *string, _a2 *runtime.ResourceLimits, _a3 bool)) *MockRepository_ListWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(*runtime.ResourceLimits), args[3].(bool))
	})
	return _c
}

func (_c *MockRepository_ListWorkloads_Call) Return(_a0 []*workload.Workload, _a1 error) *MockRepository_ListWorkloads_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListWorkloads_Call) RunAndReturn(run func(context.Context, *string, *runtime.ResourceLimits, bool) ([]*workload.Workload, error)) *MockRepository_ListWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvent provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) SaveEvent(_a0 context.Context, _a1 workload.Event) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, workload.Event) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SaveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvent'
type MockRepository_SaveEvent_Call struct {
	*mock.Call
}

// SaveEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 workload.Event
func (_e *MockRepository_Expecter) SaveEvent(_a0 interface{}, _a1 interface{}) *MockRepository_SaveEvent_Call {
	return &MockRepository_SaveEvent_Call{Call: _e.mock.On("SaveEvent", _a0, _a1)}
}

func (_c *MockRepository_SaveEvent_Call) Run(run func(_a0 context.Context, _a1 workload.Event)) *MockRepository_SaveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(workload.Event))
	})
	return _c
}

func (_c *MockRepository_SaveEvent_Call) Return(_a0 error) *MockRepository_SaveEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SaveEvent_Call) RunAndReturn(run func(context.Context, workload.Event) error) *MockRepository_SaveEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLease provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRepository) UpdateLease(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLease'
type MockRepository_UpdateLease_Call struct {
	*mock.Call
}

// UpdateLease is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockRepository_Expecter) UpdateLease(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockRepository_UpdateLease_Call {
	return &MockRepository_UpdateLease_Call{Call: _e.mock.On("UpdateLease", _a0, _a1, _a2)}
}

func (_c *MockRepository_UpdateLease_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockRepository_UpdateLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateLease_Call) Return(_a0 error) *MockRepository_UpdateLease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateLease_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_UpdateLease_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertLease provides a mock function with given fields: ctx, nodeID, workloadID
func (_m *MockRepository) UpsertLease(ctx context.Context, nodeID string, workloadID string) (*workload.Lease, error) {
	ret := _m.Called(ctx, nodeID, workloadID)

	if len(ret) == 0 {
		panic("no return value specified for UpsertLease")
	}

	var r0 *workload.Lease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*workload.Lease, error)); ok {
		return rf(ctx, nodeID, workloadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *workload.Lease); ok {
		r0 = rf(ctx, nodeID, workloadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workload.Lease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, nodeID, workloadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpsertLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertLease'
type MockRepository_UpsertLease_Call struct {
	*mock.Call
}

// UpsertLease is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID string
//   - workloadID string
func (_e *MockRepository_Expecter) UpsertLease(ctx interface{}, nodeID interface{}, workloadID interface{}) *MockRepository_UpsertLease_Call {
	return &MockRepository_UpsertLease_Call{Call: _e.mock.On("UpsertLease", ctx, nodeID, workloadID)}
}

func (_c *MockRepository_UpsertLease_Call) Run(run func(ctx context.Context, nodeID string, workloadID string)) *MockRepository_UpsertLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpsertLease_Call) Return(_a0 *workload.Lease, _a1 error) *MockRepository_UpsertLease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpsertLease_Call) RunAndReturn(run func(context.Context, string, string) (*workload.Lease, error)) *MockRepository_UpsertLease_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
