// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dbutils "github.com/wernsiet/morchy/pkg/db.utils"

	workload "github.com/wernsiet/morchy/pkg/controlplane/domain/workload"
)

// MockRepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type MockRepositoryFactory struct {
	mock.Mock
}

type MockRepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryFactory) EXPECT() *MockRepositoryFactory_Expecter {
	return &MockRepositoryFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields: _a0
func (_m *MockRepositoryFactory) New(_a0 dbutils.DB) workload.Repository {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 workload.Repository
	if rf, ok := ret.Get(0).(func(dbutils.DB) workload.Repository); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workload.Repository)
		}
	}

	return r0
}

// MockRepositoryFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockRepositoryFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - _a0 dbutils.DB
func (_e *MockRepositoryFactory_Expecter) New(_a0 interface{}) *MockRepositoryFactory_New_Call {
	return &MockRepositoryFactory_New_Call{Call: _e.mock.On("New", _a0)}
}

func (_c *MockRepositoryFactory_New_Call) Run(run func(_a0 dbutils.DB)) *MockRepositoryFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dbutils.DB))
	})
	return _c
}

func (_c *MockRepositoryFactory_New_Call) Return(_a0 workload.Repository) *MockRepositoryFactory_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryFactory_New_Call) RunAndReturn(run func(dbutils.DB) workload.Repository) *MockRepositoryFactory_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryFactory creates a new instance of MockRepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryFactory {
	mock := &MockRepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
