definitions:
  jsonformatter.EventCreateRequest:
    type: object
  jsonformatter.LeaseResponse:
    properties:
      created_at:
        example: 2025-11-03T13:45:00+03
        type: string
      node_id:
        example: some-node-id
        type: string
      updated_at:
        example: 2025-11-03T13:45:00+03
        type: string
      workload_id:
        example: some-workload-id
        type: string
    type: object
  jsonformatter.WorkloadResponse:
    properties:
      container:
        $ref: '#/definitions/runtime.Container'
      id:
        example: some-uuid
        type: string
      status:
        example: new
        type: string
    type: object
  jsonformatter.WorkloadSpecRequest:
    properties:
      command:
        items:
          type: string
        type: array
      cpu:
        type: integer
      env:
        additionalProperties:
          type: string
        type: object
      image:
        type: string
      ram:
        type: integer
    type: object
  runtime.Container:
    properties:
      command:
        items:
          type: string
        type: array
      env:
        items:
          $ref: '#/definitions/runtime.EnvVar'
        type: array
      image:
        type: string
      labels:
        additionalProperties:
          type: string
        type: object
      name:
        type: string
      resources:
        $ref: '#/definitions/runtime.ResourceLimits'
    type: object
  runtime.EnvVar:
    properties:
      name:
        type: string
      value:
        type: string
    type: object
  runtime.ResourceLimits:
    properties:
      cpu:
        type: integer
      ram:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/events:
    post:
      consumes:
      - application/json
      description: Create a new event for a node
      parameters:
      - description: Node ID
        in: query
        name: node_id
        required: true
        type: string
      - description: Event payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/jsonformatter.EventCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Push event
      tags:
      - events
  /api/v1/workloads:
    get:
      consumes:
      - application/json
      description: Retrieve a list of workloads filtered by status, CPU, and RAM
      parameters:
      - description: Filter by workload status
        example: new
        in: query
        name: status
        type: string
      - description: Filter by CPU (millicores)
        example: 100
        in: query
        name: cpu
        type: integer
      - description: Filter by RAM (MB)
        example: 256
        in: query
        name: ram
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/jsonformatter.WorkloadResponse'
            type: array
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List workloads
      tags:
      - workloads
    post:
      consumes:
      - application/json
      description: Create a new workload from provided spec
      parameters:
      - description: Workload specification
        in: body
        name: workloadSpec
        required: true
        schema:
          $ref: '#/definitions/jsonformatter.WorkloadSpecRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/jsonformatter.WorkloadResponse'
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create workload
      tags:
      - workloads
  /api/v1/workloads/{workload_id}:
    delete:
      consumes:
      - application/json
      description: Delete a workload and all related models (lease, spec)
      parameters:
      - description: Workload ID
        in: path
        minLength: 1
        name: workload_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete workload
      tags:
      - workloads
    get:
      consumes:
      - application/json
      description: Retrieve a single workload by ID
      parameters:
      - description: Workload ID
        in: path
        minLength: 1
        name: workload_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jsonformatter.WorkloadResponse'
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get workload
      tags:
      - workloads
  /api/v1/workloads/{workload_id}/lease:
    delete:
      consumes:
      - application/json
      description: Release/delete a lease for a specific workload on a given node
      parameters:
      - description: Workload ID
        in: path
        minLength: 1
        name: workload_id
        required: true
        type: string
      - description: Node ID
        in: query
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Release a lease
      tags:
      - leases
    put:
      consumes:
      - application/json
      description: Extend a lease for a specific workload on a given node
      parameters:
      - description: Workload ID
        in: path
        minLength: 1
        name: workload_id
        required: true
        type: string
      - description: Node ID
        in: query
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jsonformatter.LeaseResponse'
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Extend a lease
      tags:
      - leases
swagger: "2.0"
